apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.nativetls.name }}
      protocol: TCP
      port: {{ .Values.service.nativetls.port }}
      targetPort: {{ .Values.service.nativetls.port }}
  selector:
    {{- include "clickhouse.selectorLabels" . | nindent 6 }}
